name = "heritage-hooves"
main = "src/index.ts"
compatibility_date = "2026-08-01"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "heritage-hooves"
database_id = "cefec735-ee58-4e7b-a63d-f11432e28e01"

[triggers]
crons = ["*/15 * * * *"]
