-- Slice 0022 §A4 step 2: the twelve acquired conditions, transcribed from migrations/0125's own
-- seed straight across into incident_types - no numbers change. risk_model drops
-- treatmentWindowGameDays/treatmentCostKey (now the two real columns beside it); every other key
-- and every probability is copied verbatim.
--
-- No semicolons and no double hyphens anywhere in these string literals (migrations/0053's own
-- warning, restated by migrations/0125 - src/lib/sql.ts's splitSqlStatements splits on every
-- literal semicolon and strips every double hyphen with no awareness of string literals).
INSERT INTO incident_types (code, name, risk_model, treatment_window_game_days, treatment_cost_key, enabled, description, event_text, sort_order) VALUES
('COLIC', 'Colic',
 '{"v":1,"kind":"acquired","tissue":"gut","robustnessTrait":null,"robustnessWeight":0,"baseRatePerGameDay":0.00025,"careWeight":1.2,"workloadWeight":0.6,"feedWeight":0,"pastureMultiplier":0.7,"outcomesUntreated":{"resolved":0.55,"manageable":0.05,"degenerative":0,"death":0.40},"outcomesTreated":{"resolved":0.90,"manageable":0.05,"degenerative":0,"death":0.05}}',
 4, 'acute_treatment_cost_colic', 1,
 'An emergency, not a genetic condition. Colic is a general term for stomach pain in horses, and one of the most common reasons a horse sees a vet. Most colic resolves with prompt care. Left alone, some cases get worse.',
 'Colic can happen to any horse, from any cause, and it is not always something an owner could have prevented, but calling the vet early gives a horse a real chance. A horse that does not survive stays in the barn''s records, in every pedigree it belongs to, exactly as it was.',
 1),
('CHOKE', 'Choke',
 '{"v":1,"kind":"acquired","tissue":"gut","robustnessTrait":null,"robustnessWeight":0,"baseRatePerGameDay":0.00008,"careWeight":1.0,"workloadWeight":0,"feedWeight":0,"pastureMultiplier":1.0,"outcomesUntreated":{"resolved":0.85,"manageable":0.10,"degenerative":0,"death":0.05},"outcomesTreated":{"resolved":0.97,"manageable":0.03,"degenerative":0,"death":0}}',
 2, 'acute_treatment_cost_choke', 1,
 'An obstruction in the oesophagus, usually from feed swallowed too fast. Uncomfortable and alarming to watch, and it usually clears with prompt attention.',
 'Choke usually resolves quickly once a vet is called. Left entirely unattended it can, rarely, turn serious.',
 2),
('ULCERS', 'Gastric ulcers',
 '{"v":1,"kind":"acquired","tissue":"gut","robustnessTrait":null,"robustnessWeight":0,"baseRatePerGameDay":0.00035,"careWeight":0.3,"workloadWeight":1.3,"feedWeight":0,"pastureMultiplier":0.6,"outcomesUntreated":{"resolved":0.10,"manageable":0.90,"degenerative":0,"death":0},"outcomesTreated":{"resolved":0.35,"manageable":0.65,"degenerative":0,"death":0}}',
 10, 'acute_treatment_cost_ulcers', 1,
 'Irritation of the stomach lining, common in horses shown or worked hard on a busy schedule. Rarely dangerous on its own, but it settles in for a while and affects how a horse eats and performs.',
 'Ulcers are common and manageable, but a busy schedule keeps bringing them back unless the pace eases up.',
 3),
('TYING_UP', 'Sporadic tying-up',
 '{"v":1,"kind":"acquired","tissue":"muscle","robustnessTrait":null,"robustnessWeight":0,"baseRatePerGameDay":0.00012,"careWeight":0.2,"workloadWeight":1.4,"feedWeight":0,"pastureMultiplier":0.7,"outcomesUntreated":{"resolved":0.60,"manageable":0.35,"degenerative":0,"death":0.05},"outcomesTreated":{"resolved":0.85,"manageable":0.15,"degenerative":0,"death":0}}',
 1, 'acute_treatment_cost_tying_up', 1,
 'A muscle cramping episode brought on by hard work, unrelated to the inherited PSSM1 that causes the same symptoms in a small number of horses. Usually a one-off, most often after a demanding stretch of showing.',
 'A one-off tying-up episode usually resolves quickly with rest and a vet''s attention. Rarely, it is more serious.',
 4),
('STRANGLES', 'Strangles',
 '{"v":1,"kind":"acquired","tissue":"respiratory","robustnessTrait":null,"robustnessWeight":0,"baseRatePerGameDay":0.00006,"careWeight":0.6,"workloadWeight":1.2,"feedWeight":0,"pastureMultiplier":1.0,"outcomesUntreated":{"resolved":0.90,"manageable":0.05,"degenerative":0,"death":0.05},"outcomesTreated":{"resolved":0.95,"manageable":0.03,"degenerative":0,"death":0.02}}',
 14, 'acute_treatment_cost_strangles', 1,
 'A contagious respiratory illness, modelled here as a risk to one horse rather than a stable-wide outbreak. A horse showing often is more exposed than one kept quietly at home.',
 'Strangles usually clears with care over a couple of weeks. A horse recovering from it cannot be shown while the illness is active.',
 5),
('ABSCESS', 'Hoof abscess / thrush',
 '{"v":1,"kind":"acquired","tissue":"foot","robustnessTrait":"foot_robustness","robustnessWeight":0.5,"baseRatePerGameDay":0.00030,"careWeight":1.3,"workloadWeight":0.2,"feedWeight":0,"pastureMultiplier":0.7,"outcomesUntreated":{"resolved":0.80,"manageable":0.15,"degenerative":0.05,"death":0},"outcomesTreated":{"resolved":0.97,"manageable":0.03,"degenerative":0,"death":0}}',
 5, 'acute_treatment_cost_abscess', 1,
 'Infection trapped in the hoof, or softening between the frog''s clefts. Common, painful while it lasts, and one of the more preventable entries on this list with regular farrier attention.',
 'Hoof abscesses and thrush usually clear up quickly once treated. Left alone for long enough, an abscess can occasionally leave lasting damage.',
 6),
('RAIN_ROT', 'Rain rot / mud fever',
 '{"v":1,"kind":"acquired","tissue":"skin","robustnessTrait":null,"robustnessWeight":0,"baseRatePerGameDay":0.00020,"careWeight":1.0,"workloadWeight":0,"feedWeight":0,"pastureMultiplier":1.8,"outcomesUntreated":{"resolved":0.85,"manageable":0.15,"degenerative":0,"death":0},"outcomesTreated":{"resolved":0.98,"manageable":0.02,"degenerative":0,"death":0}}',
 10, 'acute_treatment_cost_skin', 1,
 'A bacterial skin condition brought on by prolonged wet, more common on a horse turned out in wet conditions for long stretches than one kept dry in a stall.',
 'Rain rot and mud fever clear up with care and drier conditions. Never fatal, but it lingers if ignored.',
 7),
('EYE_INJURY', 'Eye injury',
 '{"v":1,"kind":"acquired","tissue":"eye","robustnessTrait":null,"robustnessWeight":0,"baseRatePerGameDay":0.00010,"careWeight":0.3,"workloadWeight":0,"feedWeight":0,"pastureMultiplier":1.3,"outcomesUntreated":{"resolved":0.70,"manageable":0.30,"degenerative":0,"death":0},"outcomesTreated":{"resolved":0.90,"manageable":0.10,"degenerative":0,"death":0}}',
 3, 'acute_treatment_cost_eye_injury', 1,
 'A scratch or knock to the eye, more likely for a horse turned out among branches, fences and other horses than one kept in a stall.',
 'Most eye injuries heal cleanly with prompt attention. Never fatal, but an eye is not something to leave and hope about.',
 8),
('LAMINITIS', 'Laminitis',
 '{"v":1,"kind":"acquired","tissue":"foot","robustnessTrait":"foot_robustness","robustnessWeight":1.0,"baseRatePerGameDay":0.00015,"careWeight":0.5,"workloadWeight":0.8,"feedWeight":1.0,"pastureMultiplier":0.7,"outcomesUntreated":{"resolved":0.30,"manageable":0.35,"degenerative":0.30,"death":0.05},"outcomesTreated":{"resolved":0.70,"manageable":0.25,"degenerative":0.04,"death":0.01}}',
 3, 'acute_treatment_cost_laminitis', 1,
 'Painful inflammation inside the hoof. Richer feed measurably raises the risk, and it is worse again for a horse whose feet were never especially strong to begin with. Left untreated it can become a permanent, career-ending problem.',
 'Laminitis is a real emergency for the hoof. Prompt treatment gives a horse a real chance of a full recovery. Left alone, it can turn into a lasting, career-ending problem, and rarely it is fatal.',
 9),
('NAVICULAR', 'Navicular syndrome',
 '{"v":1,"kind":"acquired","tissue":"foot","robustnessTrait":"foot_robustness","robustnessWeight":1.0,"baseRatePerGameDay":0.00012,"careWeight":0.2,"workloadWeight":1.3,"feedWeight":0,"pastureMultiplier":0.7,"outcomesUntreated":{"resolved":0.20,"manageable":0.55,"degenerative":0.25,"death":0},"outcomesTreated":{"resolved":0.45,"manageable":0.50,"degenerative":0.05,"death":0}}',
 7, 'acute_treatment_cost_navicular', 1,
 'Wear-related pain deep in the heel, more likely on a heavily campaigned horse and worse again for one whose feet were never especially strong. Rarely resolves cleanly on its own, but it responds well to early management.',
 'Navicular syndrome usually settles into an ongoing management plan rather than clearing entirely. Caught early, most horses stay sound with care. Left alone, it can become permanent.',
 10),
('OSTEOARTHRITIS', 'Osteoarthritis',
 '{"v":1,"kind":"acquired","tissue":"joint","robustnessTrait":"joint_robustness","robustnessWeight":1.0,"baseRatePerGameDay":0.00010,"careWeight":0.2,"workloadWeight":1.3,"feedWeight":0,"pastureMultiplier":0.7,"outcomesUntreated":{"resolved":0.15,"manageable":0.60,"degenerative":0.25,"death":0},"outcomesTreated":{"resolved":0.35,"manageable":0.60,"degenerative":0.05,"death":0}}',
 7, 'acute_treatment_cost_osteoarthritis', 1,
 'Wear-related joint pain, most likely on a heavily campaigned horse and worse again for one whose joints were never especially strong. Rarely resolves entirely, but responds well to early management.',
 'Osteoarthritis usually settles into an ongoing management plan rather than clearing entirely. Caught early, most horses stay comfortable with care. Left alone, it can become permanent.',
 11),
('SUSPENSORY', 'Suspensory ligament injury',
 '{"v":1,"kind":"acquired","tissue":"ligament","robustnessTrait":"ligament_robustness","robustnessWeight":1.0,"baseRatePerGameDay":0.00010,"careWeight":0.2,"workloadWeight":1.4,"feedWeight":0,"pastureMultiplier":0.7,"outcomesUntreated":{"resolved":0.25,"manageable":0.35,"degenerative":0.40,"death":0},"outcomesTreated":{"resolved":0.55,"manageable":0.35,"degenerative":0.10,"death":0}}',
 5, 'acute_treatment_cost_suspensory', 1,
 'A strain to the ligament supporting the back of the leg, most likely on a heavily campaigned horse and worse again for one whose ligaments were never especially strong. A real risk of a career-ending injury if it is not caught early.',
 'A suspensory injury needs prompt rest and treatment to have the best chance of healing well. Left alone, it can end a horse''s showing career for good.',
 12);
