// The NPC show barn (slice 0008 §2.2/§5.7): one fixed stable of real, stored Quarter Horses that
// fills out a class's field, generated by the same founding-stock generator real founding stock
// uses and scored by exactly the same code as a player's own horses (CLAUDE.md §13's "no parallel
// scoring path" rule). It never breeds, ages out, dies, gets bought, sold, or improves in this
// slice - stockShowBarn below is the only thing that ever adds horses to it, and only when an
// admin presses the button at /admin/shows.

import type { Env } from '../types';
import { randomSeed, deriveSeed, makeRng } from '../lib/rng';
import type { Config } from '../lib/config-cache';
import type { StableRow } from './stables';
import { getBreeds } from './breeds';
import { buildFoundingHorseInsertStatements, countAliveHorses } from './horses';
import { parseAllelePool } from '../engines/founding/pool';
import { generateCandidate } from '../engines/founding/generate';
import { generateFoundingName } from '../engines/founding/names';
import { getEnabledConditions, getLethalTriggers } from './health';

/** One documented magic string, matching migrations/0040_npc_show_barn.sql - replaced by a proper
 * npc_policy row when the NPC stage lands (CLAUDE.md §11's founding-stock entry uses the same
 * pattern for its own magic string). */
export const SHOW_BARN_PREFIX = 'Fair Meadow';

export async function getShowBarnStable(env: Env): Promise<StableRow | null> {
  return env.DB.prepare('SELECT * FROM stables WHERE prefix = ? AND is_npc = 1').bind(SHOW_BARN_PREFIX).first<StableRow>();
}

/** Walks generateFoundingName's own deterministic sequence forward on a collision (slice 0005 §6.5's
 * resolveUniqueName, reused here rather than duplicated with different behaviour). */
async function resolveUniqueBarnName(env: Env, seed: number): Promise<{ registeredName: string; originPrefix: string }> {
  let attempt = 0;
  for (;;) {
    const { originPrefix, namePart } = generateFoundingName(seed, attempt);
    const registeredName = `${originPrefix} ${namePart}`;
    const existing = await env.DB.prepare('SELECT id FROM horses WHERE registered_name = ?').bind(registeredName).first<{ id: number }>();
    if (!existing) return { registeredName, originPrefix };
    attempt++;
  }
}

export interface StockShowBarnResult {
  minted: number;
  alreadyHad: number;
}

/**
 * Tops the barn up to targetSize Quarter Horses at the given quality band - idempotent in the
 * sense that pressing the button twice never over-fills it (slice 0008 §8.2), because it only ever
 * mints the shortfall. Sex is an even coin flip per candidate; this slice's class has no
 * sex_restriction, so the mix doesn't need to match any particular ratio.
 */
export async function stockShowBarn(
  env: Env,
  params: { config: Config; gameDay: number; worldTickSeq: number; targetSize: number; band: string }
): Promise<StockShowBarnResult> {
  const stable = await getShowBarnStable(env);
  if (!stable) {
    throw new Error('stockShowBarn: the NPC show barn stable is missing - has migrations/0040_npc_show_barn.sql been applied?');
  }

  const alreadyHad = await countAliveHorses(env, stable.id);
  const shortfall = Math.max(0, params.targetSize - alreadyHad);
  if (shortfall === 0) return { minted: 0, alreadyHad };

  const breeds = await getBreeds(env);
  const qh = breeds.find((b) => b.code === 'QH');
  if (!qh) throw new Error('stockShowBarn: the Quarter Horse breed is missing');
  const pool = parseAllelePool(qh.founding_allele_pool);

  const polygenicOneChance = params.config.values.quality_bands[params.band];
  if (polygenicOneChance === undefined) throw new Error(`stockShowBarn: unknown quality band "${params.band}"`);

  const [conditions, lethalTriggers] = await Promise.all([getEnabledConditions(env), getLethalTriggers(env)]);

  const statements = [];
  for (let i = 0; i < shortfall; i++) {
    const seed = randomSeed();
    const generated = generateCandidate({
      pool,
      polygenicOneChance,
      ageMinGameDays: params.config.values.founding_age_min_game_days,
      ageMaxGameDays: params.config.values.founding_age_max_game_days,
      seed,
      lethalTriggers,
    });
    const sex = makeRng(deriveSeed(seed, 'sex')).pick(['mare', 'stallion'] as const);
    const { registeredName, originPrefix } = await resolveUniqueBarnName(env, seed);

    statements.push(
      ...buildFoundingHorseInsertStatements(env, {
        stableId: stable.id,
        sex,
        breedId: qh.id,
        breedCode: qh.code,
        registeredName,
        breederPrefix: originPrefix,
        bornGameDay: params.gameDay - generated.ageGameDays,
        genotype: generated.genotype,
        rngSeed: seed,
        worldTickSeq: params.worldTickSeq,
        estrousCycleTicks: params.config.values.estrous_cycle_ticks,
        conformationNoiseSd: params.config.values.conformation_noise_sd,
        conditions,
        lethalFoalDeathGameDays: params.config.values.lethal_foal_death_game_days,
        // The NPC show barn has no account (SHOW_BARN_PREFIX's own file comment) - null here means
        // buildConditionSignsEventStatement's own guard writes nothing, which is correct: its
        // horses foal nothing a child reads (this file's header comment).
        accountId: null,
        // Slice 0011 §2.3/§7.1: the show barn's horses age and die on the same code path as
        // everyone else's (CLAUDE.md §13) - a lifespan is rolled for them here exactly like anyone
        // else's founding stock.
        lifespanConfig: params.config.values,
        // Slice 0013 §2.6/§5.2: the show barn's horses are stamped current every tick regardless
        // (noticeCareDue), but starting them current here too means they never read as overdue for
        // even the one tick between minting and the next tick running.
        careStartAgeGameDays: params.config.values.care_start_age_game_days,
        currentGameDay: params.gameDay,
      })
    );
  }

  await env.DB.batch(statements);
  return { minted: shortfall, alreadyHad };
}
