// The NPC show barn (slice 0008 §2.2/§5.7, split from the QH volume breeder by slice 0026 stage 4
// §4.1): one stable of real, stored horses that fills out a class's field, generated by the same
// founding-stock generator real founding stock uses and scored by exactly the same code as a
// player's own horses (CLAUDE.md §13's "no parallel scoring path" rule). It never breeds, ages and
// dies deterministically (§4.6), never improves - topUpShowBarnToPlan below (run every tick, and
// from the "Restock show barn to plan" button at /admin/shows) is the only thing that ever adds
// horses to it, always to the rank plan in config's npc_show_barn_rank_plan.

import type { Env } from '../types';
import { randomSeed, deriveSeed, makeRng } from '../lib/rng';
import type { Config } from '../lib/config-cache';
import type { StableRow } from './stables';
import { getStableById } from './stables';
import { getBreeds, getBreedsInPlay, type BreedRow } from './breeds';
import { buildFoundingHorseInsertStatements, countAliveHorses, type HorseRow } from './horses';
import { parseAllelePool } from '../engines/founding/pool';
import { generateCandidate } from '../engines/founding/generate';
import { parseIdealVector } from '../engines/showing/score';
import { parseAbilityBias, parseDisciplineAptitudes } from '../engines/breeds/identity';
import { getSpecializableAbilityTraits, getEnabledDisciplines } from './disciplines';
import { generateFoundingName } from '../engines/founding/names';
import { getEnabledConditions, getLethalTriggers } from './health';
import type { ShowRank } from '../engines/showing/eligibility';

/** Slice 0026 stage 4 §4.1/§4.2: the show-barn role, split off the Quarter Horse volume breeder it
 * used to double as. Originally seeded as 'Fair Meadow' by migrations/0040_npc_show_barn.sql,
 * renamed to 'Apples and Oats Ranch' by migration 0136 when it took on the volume-breeder role too
 * (migration 0085) - migration 0172 creates a fresh stable under a new name/prefix, with no
 * npc_policy row (so it is never a breeding target). NOT 'Fair Meadow' - despite §4.2's "prefix Fair
 * Meadow, free again", stable_prefix_history.prefix is UNIQUE with no scoping to "currently active"
 * (that table's own header comment: a retired prefix is never reissued), and migration 0136 already
 * closed 'Fair Meadow' there permanently. See migration 0172's own comment for the departure. */
export const SHOW_BARN_PREFIX = 'Fair Meadow Show Barn';

/** The Quarter Horse volume breeder (slice 0015 §2.1), seeded as 'Fair Meadow' by migration 0040
 * and renamed here by migration 0136 - named as its own constant (rather than reusing
 * SHOW_BARN_PREFIX, which now names the separate show-barn stable) because src/db/reset.ts has to
 * recreate it under its own npc_policy row on a full world reset. */
export const QH_VOLUME_BREEDER_PREFIX = 'Apples and Oats Ranch';

/** Slice 0015 §2.1/§5.3: the Quarter Horse conformation specialist and discipline barn, originally
 * seeded as 'Cedar Hollow'/'Willow Creek Barrels' by migrations/0085_npc_stables_and_policies.sql,
 * renamed to 'Bronco Valley'/'Horseshoe Bay' by migration 0136 (slice 0023, an operator naming
 * decision). Named here, not just in the migration, because a full world reset (src/db/reset.ts) has
 * to recreate both stables, and that migration never runs again. */
export const QH_CONFORMATION_SPECIALIST_PREFIX = 'Bronco Valley';
export const QH_DISCIPLINE_BARN_PREFIX = 'Horseshoe Bay';

/** Slice 0023: the six new Paso Fino and German Warmblood personality stables, seeded by
 * migrations/0130_npc_stables_paso_fino_and_german_warmblood.sql. Named here for the same reason as
 * the Quarter Horse trio above - a full world reset has to recreate all nine. */
export const PF_CONFORMATION_SPECIALIST_PREFIX = 'Carrot Cove';
export const PF_DISCIPLINE_BARN_PREFIX = 'Honeycomb Hills';
export const PF_VOLUME_BREEDER_PREFIX = 'Reese Puff Horses';
export const GW_CONFORMATION_SPECIALIST_PREFIX = 'Queens Palace';
export const GW_DISCIPLINE_BARN_PREFIX = 'Springen Stables';
export const GW_VOLUME_BREEDER_PREFIX = 'Suchon Acres';

/** A second German Warmblood discipline barn, targeting Dressage rather than Show Jumping, seeded
 * by migrations/0168_npc_stable_gw_dressage.sql - the breed's own discipline_aptitudes row
 * (migration 0144) rates it nearly as well suited to dressage (1.04) as to jumping (1.05), so a
 * second discipline barn is a real competitor rather than a padded one. Named here for the same
 * reason as the pairs above - a full world reset has to recreate it. */
export const GW_DRESSAGE_BARN_PREFIX = 'Dressur Stables';

export async function getShowBarnStable(env: Env): Promise<StableRow | null> {
  return env.DB.prepare('SELECT * FROM stables WHERE prefix = ? AND is_npc = 1').bind(SHOW_BARN_PREFIX).first<StableRow>();
}

/** Slice 0026 stage 4 §4.4: the class_key/rank rows a show-barn horse is seeded with at mint,
 * written by mintFoundingHorses below via buildShowBarnRankSeedStatement - never earned, and never
 * updated again (§4.5 has judgeOneClass skip the graduation upsert for any horse this stable owns). */
export interface ShowBarnRankSeedClassKey {
  classKey: string;
  classType: 'breed_conformation' | 'discipline';
  breedId: number | null;
  disciplineCode: string | null;
}

/** The seed-time counterpart to src/db/shows.ts's buildRankProgressionUpsertStatement - that one
 * computes a graduation from placings; this one just writes the starting row a show-barn horse is
 * minted with, which is why it lives here beside the mint rather than there beside judging. Uses the
 * same "(SELECT id FROM horses ORDER BY id DESC LIMIT 1)" trick buildHorseConditionStatements
 * (src/db/health.ts) uses, for the same reason: called immediately after this same horse's own
 * insert, within one batch, before anything else touches `horses`. */
function buildShowBarnRankSeedStatement(
  env: Env,
  params: { classKey: ShowBarnRankSeedClassKey; rank: ShowRank; gameDay: number }
): D1PreparedStatement {
  return env.DB.prepare(
    `INSERT INTO horse_class_ranks (horse_id, class_type, breed_id, discipline_code, class_key, rank, top3_since_promotion, wins_since_promotion, updated_game_day)
     VALUES ((SELECT id FROM horses ORDER BY id DESC LIMIT 1), ?, ?, ?, ?, ?, 0, 0, ?)`
  ).bind(params.classKey.classType, params.classKey.breedId, params.classKey.disciplineCode, params.classKey.classKey, params.rank, params.gameDay);
}

/** Slice 0026 stage 4 §4.4/§4.9: which class_keys a show-barn horse of this breed should be seeded
 * a rank for - its own breed's conformation key, always, plus every enabled discipline where the
 * breed's own discipline_aptitudes reads above neutral (1.00). A breed with no discipline above
 * neutral (Arabian, not yet enabled, is the only one today) seeds conformation only - see §4.4's own
 * "no fallback" note: a thin field for an uncovered discipline is a true statement, not a bug. */
async function showBarnRankSeedClassKeysForBreed(env: Env, breed: BreedRow): Promise<ShowBarnRankSeedClassKey[]> {
  const aptitudes = parseDisciplineAptitudes(breed.discipline_aptitudes);
  const disciplines = await getEnabledDisciplines(env);
  return [
    { classKey: `bc:${String(breed.id)}`, classType: 'breed_conformation', breedId: breed.id, disciplineCode: null },
    ...disciplines
      .filter((d) => (aptitudes[d.code] ?? 1.0) > 1.0)
      .map((d): ShowBarnRankSeedClassKey => ({ classKey: `disc:${d.code}`, classType: 'discipline', breedId: null, disciplineCode: d.code })),
  ];
}

/** Walks generateFoundingName's own deterministic sequence forward on a collision (slice 0005 §6.5's
 * resolveUniqueName, reused here rather than duplicated with different behaviour). */
async function resolveUniqueBarnName(env: Env, seed: number): Promise<{ registeredName: string; originPrefix: string }> {
  let attempt = 0;
  for (;;) {
    const { originPrefix, namePart } = generateFoundingName(seed, attempt);
    const registeredName = `${originPrefix} ${namePart}`;
    const existing = await env.DB.prepare('SELECT id FROM horses WHERE registered_name = ?').bind(registeredName).first<{ id: number }>();
    if (!existing) return { registeredName, originPrefix };
    attempt++;
  }
}

/**
 * Slice 0015 §2.7/§7.2: an NPC-bred foal is named at birth, from its own breeder stable's prefix -
 * nobody will ever name it by hand the way a player names their own foal. Walks the identical
 * deterministic collision sequence resolveUniqueBarnName uses above, seeded from the foal's own
 * foal_rng_seed so re-deriving it (a retried tick) always produces the same name. Only namePart is
 * used - generateFoundingName's own originPrefix means "founding origin" (bred by someone outside
 * the game), which would misdescribe a horse this stable bred itself.
 */
export async function resolveUniqueNpcFoalName(env: Env, prefix: string, seed: number): Promise<string> {
  let attempt = 0;
  for (;;) {
    const { namePart } = generateFoundingName(seed, attempt);
    const registeredName = `${prefix} ${namePart}`;
    const existing = await env.DB.prepare('SELECT id FROM horses WHERE registered_name = ?').bind(registeredName).first<{ id: number }>();
    if (!existing) return registeredName;
    attempt++;
  }
}

export interface StockShowBarnResult {
  minted: number;
  alreadyHad: number;
}

/**
 * The mechanism underneath topUpShowBarnToPlan and stockNpcStable below (slice 0015 §7.3): both the
 * stable and the breed are parameters here, which is what "both become parameters" (the slice
 * document's own words) actually means. Mints exactly `count` horses, no top-up logic - the two
 * callers below each decide what `count` should be for their own purpose.
 *
 * Slice 0026 stage 4 §4.6: whenever `params.stable` IS the show barn, this applies its two special
 * mint rules automatically (a wider age spread, and a death day fixed at the exact day age decline
 * would otherwise start) rather than needing every caller to ask for them - so an admin adding show-
 * barn stock through the generic outcross form (below) gets the same treatment as the plan-aware
 * top-up does, with no way to mint a show-barn horse that ages and dies like anyone else's stock.
 * `rankSeed` is separate because only a caller that already knows a target rank (topUpShowBarnToPlan)
 * can supply it - a manual outcross into the show barn mints horses that start at Novice.
 */
async function mintFoundingHorses(
  env: Env,
  params: {
    stable: StableRow;
    breed: BreedRow;
    config: Config;
    gameDay: number;
    worldTickSeq: number;
    count: number;
    band: string;
    rankSeed?: { classKeys: ShowBarnRankSeedClassKey[]; rank: ShowRank };
  }
): Promise<number> {
  if (params.count <= 0) return 0;

  const isShowBarn = params.stable.prefix === SHOW_BARN_PREFIX;
  const ageMinGameDays = isShowBarn ? params.config.values.npc_show_barn_age_min_game_days : params.config.values.founding_age_min_game_days;
  const ageMaxGameDays = isShowBarn ? params.config.values.npc_show_barn_age_max_game_days : params.config.values.founding_age_max_game_days;

  const pool = parseAllelePool(params.breed.founding_allele_pool);
  const polygenicOneChance = params.config.values.quality_bands[params.band];
  if (polygenicOneChance === undefined) throw new Error(`mintFoundingHorses: unknown quality band "${params.band}"`);

  const [conditions, lethalTriggers, eligibleAbilityTraits] = await Promise.all([
    getEnabledConditions(env),
    getLethalTriggers(env),
    getSpecializableAbilityTraits(env),
  ]);
  // 2026-08-04, operator decision: NPC stock is generated exactly the way player stock is. Until
  // now this call passed neither the ideal vector nor the eligible ability traits, so slice 0019's
  // founding specialists reached every founding, claimed and consigned horse in the game EXCEPT the
  // ones NPC stables mint - which meant a player's stock was systematically better than the field
  // it competed against, in both conformation and ability, for reasons nothing had written down.
  //
  // This raises NPC quality, which is the one thing CLAUDE.md §13 singles out as most likely to
  // kill the project if it drifts unwatched. It is bounded rather than open-ended (a specialist is
  // one trait at a fixed potential, not a ceiling that climbs), and npc_policy's quality ceiling
  // still applies to everything these stables BREED. Watch the outcome distribution at /admin/npc.
  const breedIdealVector = params.breed.ideal_vector ? parseIdealVector(params.breed.ideal_vector) : null;
  // Migration 0141: and their breed leaning, the same as every other generation path.
  const abilityBias = parseAbilityBias(params.breed.ability_bias);

  const statements = [];
  for (let i = 0; i < params.count; i++) {
    const seed = randomSeed();
    const generated = generateCandidate({
      pool,
      polygenicOneChance,
      robustnessOneChance: params.config.values.robustness_one_chance,
      ageMinGameDays,
      ageMaxGameDays,
      seed,
      lethalTriggers,
      breedIdealVector,
      eligibleAbilityTraits,
      abilitySpecialistPotential: params.config.values.founding_ability_specialist_potential,
      abilityBias,
    });
    const sex = makeRng(deriveSeed(seed, 'sex')).pick(['mare', 'stallion'] as const);
    const { registeredName, originPrefix } = await resolveUniqueBarnName(env, seed);
    const bornGameDay = params.gameDay - generated.ageGameDays;
    // Slice 0026 stage 4 §4.6: "they die at decline start" - a show-barn horse's death day is fixed
    // at the exact game day age decline would otherwise begin, not rolled from its own seed, so it
    // competes at a 1.0 age modifier its whole life and dies the day it would first be penalised.
    // Snapshotted here rather than read at death time (CLAUDE.md §5.5) - retuning the decline curve
    // later must not retroactively kill or resurrect the barn.
    const naturalDeathGameDayOverride = isShowBarn ? bornGameDay + params.config.values.age_decline_start_game_days : undefined;

    statements.push(
      ...buildFoundingHorseInsertStatements(env, {
        stableId: params.stable.id,
        sex,
        breedId: params.breed.id,
        breedCode: params.breed.code,
        registeredName,
        breederPrefix: originPrefix,
        bornGameDay,
        genotype: generated.genotype,
        rngSeed: seed,
        worldTickSeq: params.worldTickSeq,
        estrousCycleTicks: params.config.values.estrous_cycle_ticks,
        conformationNoiseSd: params.config.values.conformation_noise_sd,
        conditions,
        lethalFoalDeathGameDays: params.config.values.lethal_foal_death_game_days,
        // No NPC stable has an account (this file's header comment) - null here means
        // buildConditionSignsEventStatement's own guard writes nothing, which is correct: its
        // horses foal nothing a child reads.
        accountId: null,
        // Slice 0011 §2.3/§7.1: an NPC stable's horses age and die on the same code path as
        // everyone else's (CLAUDE.md §13) - a lifespan is rolled for them here exactly like anyone
        // else's founding stock, unless naturalDeathGameDayOverride above says otherwise.
        lifespanConfig: params.config.values,
        naturalDeathGameDayOverride,
        // Slice 0013 §2.6/§5.2: an NPC stable's horses are stamped current every tick regardless
        // (noticeCareDue), but starting them current here too means they never read as overdue for
        // even the one tick between minting and the next tick running.
        careStartAgeGameDays: params.config.values.care_start_age_game_days,
        currentGameDay: params.gameDay,
      })
    );

    // Slice 0026 stage 4 §4.4: written at mint, never earned - only for the plan-aware top-up below,
    // which is the only caller that knows what rank to seed. Pushed right after this same horse's
    // own insert (and its condition rows, if any), before the next horse's insert - the
    // "(SELECT id FROM horses ORDER BY id DESC LIMIT 1)" trick buildShowBarnRankSeedStatement uses
    // only works within that ordering.
    if (params.rankSeed) {
      for (const classKey of params.rankSeed.classKeys) {
        statements.push(buildShowBarnRankSeedStatement(env, { classKey, rank: params.rankSeed.rank, gameDay: params.gameDay }));
      }
    }
  }

  await env.DB.batch(statements);
  return params.count;
}

/**
 * Slice 0026 stage 4 §4.3/§4.7: tops the show barn up to the rank plan (config's
 * npc_show_barn_rank_plan - novice/open/champion counts, each at its own quality band), one breed at
 * a time, for every breed in play with an ideal vector. Idempotent in the sense that running it
 * against a full barn mints nothing, because it only ever mints each (breed, rank)'s own shortfall -
 * called every tick (before judging, so a class judged this tick sees a barn already refilled) and
 * from the "Restock show barn to plan" button at /admin/shows.
 */
export async function topUpShowBarnToPlan(
  env: Env,
  params: { config: Config; gameDay: number; worldTickSeq: number }
): Promise<StockShowBarnResult> {
  const stable = await getShowBarnStable(env);
  if (!stable) {
    throw new Error('topUpShowBarnToPlan: the NPC show barn stable is missing - has migrations/0172_show_barn_split.sql been applied?');
  }
  const breeds = (await getBreedsInPlay(env)).filter((b) => b.ideal_vector !== null);
  if (breeds.length === 0) return { minted: 0, alreadyHad: 0 };

  const plan = params.config.values.npc_show_barn_rank_plan;
  const countsByBreedAndRank = await countShowBarnByBreedAndRank(env, stable.id);

  let minted = 0;
  let alreadyHad = 0;
  for (const breed of breeds) {
    const classKeys = await showBarnRankSeedClassKeysForBreed(env, breed);
    for (const entry of plan) {
      const had = countsByBreedAndRank.get(`${String(breed.id)}:${entry.rank}`) ?? 0;
      alreadyHad += had;
      const shortfall = Math.max(0, entry.count - had);
      minted += await mintFoundingHorses(env, {
        stable,
        breed,
        config: params.config,
        gameDay: params.gameDay,
        worldTickSeq: params.worldTickSeq,
        count: shortfall,
        band: entry.band,
        rankSeed: { classKeys, rank: entry.rank },
      });
    }
  }
  return { minted, alreadyHad };
}

/** Slice 0026 stage 4 §4.3: this stable's own alive horses, grouped by breed and by the rank each
 * one holds in its own breed's conformation class_key ('bc:<breedId>', which every show-barn horse
 * is always seeded a row for - §4.4) - the top-up's own shortfall axis. Keyed "<breedId>:<rank>". */
export async function countShowBarnByBreedAndRank(env: Env, stableId: number): Promise<Map<string, number>> {
  const result = await env.DB
    .prepare(
      `SELECT h.breed_id AS breedId, COALESCE(hcr.rank, 'novice') AS rank, COUNT(*) AS n
       FROM horses h
       LEFT JOIN horse_class_ranks hcr ON hcr.horse_id = h.id AND hcr.class_key = 'bc:' || h.breed_id
       WHERE h.owner_stable_id = ? AND h.status = 'alive'
       GROUP BY h.breed_id, rank`
    )
    .bind(stableId)
    .all<{ breedId: number; rank: string; n: number }>();
  const map = new Map<string, number>();
  for (const row of result.results ?? []) map.set(`${String(row.breedId)}:${row.rank}`, row.n);
  return map;
}

/**
 * Slice 0015 §3.3/§7.3: "add an outcross batch" - the only way genetic material enters an NPC
 * stable's closed population (breeding stays same-stable-only, so left alone an NPC stable's own
 * COI only ever climbs). The generalised form of the mechanism underneath topUpShowBarnToPlan: any
 * NPC stable, any breed with an ideal vector, picked from /admin/npc rather than hardcoded - and,
 * unlike topUpShowBarnToPlan's top-up-to-a-target shape, mints exactly `count` new horses regardless
 * of how many the stable already has, since "add a batch" is not "top up to a total". Also the
 * escape hatch for adding show-barn stock ad hoc (mintFoundingHorses still applies §4.6's age spread
 * and death-day override automatically when `stableId` names the show barn) - it just starts any
 * horse minted this way at Novice, since only the plan-aware top-up above knows what rank to seed.
 */
export async function stockNpcStable(
  env: Env,
  params: { stableId: number; breedId: number; config: Config; gameDay: number; worldTickSeq: number; count: number; band: string }
): Promise<StockShowBarnResult> {
  const stable = await getStableById(env, params.stableId);
  if (!stable || stable.is_npc !== 1) throw new Error(`stockNpcStable: NPC stable ${String(params.stableId)} not found`);
  const breeds = await getBreeds(env);
  const breed = breeds.find((b) => b.id === params.breedId);
  if (!breed) throw new Error(`stockNpcStable: breed ${String(params.breedId)} not found`);

  const alreadyHad = await countAliveHorses(env, stable.id);
  const minted = await mintFoundingHorses(env, { stable, breed, config: params.config, gameDay: params.gameDay, worldTickSeq: params.worldTickSeq, count: params.count, band: params.band });
  return { minted, alreadyHad };
}

/** Slice 0015 §7.1: every is_npc stable's alive horses, for judgeOneClass's show-field top-up -
 * generalised from getShowBarnStable's single hardcoded stable to "every NPC stable's stock". */
export async function listNpcStableHorses(env: Env): Promise<HorseRow[]> {
  const result = await env.DB.prepare(
    `SELECT h.* FROM horses h JOIN stables s ON s.id = h.owner_stable_id WHERE s.is_npc = 1 AND h.status = 'alive'`
  ).all<HorseRow>();
  return result.results ?? [];
}
