// The NPC show barn (slice 0008 §2.2/§5.7): one fixed stable of real, stored Quarter Horses that
// fills out a class's field, generated by the same founding-stock generator real founding stock
// uses and scored by exactly the same code as a player's own horses (CLAUDE.md §13's "no parallel
// scoring path" rule). It never breeds, ages out, dies, gets bought, sold, or improves in this
// slice - stockShowBarn below is the only thing that ever adds horses to it, and only when an
// admin presses the button at /admin/shows.

import type { Env } from '../types';
import { randomSeed, deriveSeed, makeRng } from '../lib/rng';
import type { Config } from '../lib/config-cache';
import type { StableRow } from './stables';
import { getStableById } from './stables';
import { getBreeds, getBreedsInPlay, type BreedRow } from './breeds';
import { buildFoundingHorseInsertStatements, countAliveHorses, countAliveHorsesByBreedForStable, type HorseRow } from './horses';
import { parseAllelePool } from '../engines/founding/pool';
import { generateCandidate } from '../engines/founding/generate';
import { generateFoundingName } from '../engines/founding/names';
import { getEnabledConditions, getLethalTriggers } from './health';

/** One documented magic string, matching migrations/0040_npc_show_barn.sql. Fair Meadow is now
 * one of three personality stables (slice 0015 §2.1) rather than the game's only NPC stable, but
 * keeps this name - nothing about its prefix, its history row, or its existing horses changes. */
export const SHOW_BARN_PREFIX = 'Fair Meadow';

/** Slice 0015 §2.1/§5.3: the conformation specialist and the discipline barn, seeded by
 * migrations/0085_npc_stables_and_policies.sql. Named here, not just in that migration, because a
 * full world reset (src/db/reset.ts) has to recreate both stables, and that migration never runs
 * again. */
export const CEDAR_HOLLOW_PREFIX = 'Cedar Hollow';
export const WILLOW_CREEK_BARRELS_PREFIX = 'Willow Creek Barrels';

export async function getShowBarnStable(env: Env): Promise<StableRow | null> {
  return env.DB.prepare('SELECT * FROM stables WHERE prefix = ? AND is_npc = 1').bind(SHOW_BARN_PREFIX).first<StableRow>();
}

/** Walks generateFoundingName's own deterministic sequence forward on a collision (slice 0005 §6.5's
 * resolveUniqueName, reused here rather than duplicated with different behaviour). */
async function resolveUniqueBarnName(env: Env, seed: number): Promise<{ registeredName: string; originPrefix: string }> {
  let attempt = 0;
  for (;;) {
    const { originPrefix, namePart } = generateFoundingName(seed, attempt);
    const registeredName = `${originPrefix} ${namePart}`;
    const existing = await env.DB.prepare('SELECT id FROM horses WHERE registered_name = ?').bind(registeredName).first<{ id: number }>();
    if (!existing) return { registeredName, originPrefix };
    attempt++;
  }
}

/**
 * Slice 0015 §2.7/§7.2: an NPC-bred foal is named at birth, from its own breeder stable's prefix -
 * nobody will ever name it by hand the way a player names their own foal. Walks the identical
 * deterministic collision sequence resolveUniqueBarnName uses above, seeded from the foal's own
 * foal_rng_seed so re-deriving it (a retried tick) always produces the same name. Only namePart is
 * used - generateFoundingName's own originPrefix means "founding origin" (bred by someone outside
 * the game), which would misdescribe a horse this stable bred itself.
 */
export async function resolveUniqueNpcFoalName(env: Env, prefix: string, seed: number): Promise<string> {
  let attempt = 0;
  for (;;) {
    const { namePart } = generateFoundingName(seed, attempt);
    const registeredName = `${prefix} ${namePart}`;
    const existing = await env.DB.prepare('SELECT id FROM horses WHERE registered_name = ?').bind(registeredName).first<{ id: number }>();
    if (!existing) return registeredName;
    attempt++;
  }
}

export interface StockShowBarnResult {
  minted: number;
  alreadyHad: number;
}

/**
 * The mechanism underneath stockShowBarn and stockNpcStable below (slice 0015 §7.3): both the
 * stable and the breed are parameters here, which is what "both become parameters" (the slice
 * document's own words) actually means. Mints exactly `count` horses, no top-up logic - the two
 * callers below each decide what `count` should be for their own purpose.
 */
async function mintFoundingHorses(
  env: Env,
  params: { stable: StableRow; breed: BreedRow; config: Config; gameDay: number; worldTickSeq: number; count: number; band: string }
): Promise<number> {
  if (params.count <= 0) return 0;

  const pool = parseAllelePool(params.breed.founding_allele_pool);
  const polygenicOneChance = params.config.values.quality_bands[params.band];
  if (polygenicOneChance === undefined) throw new Error(`mintFoundingHorses: unknown quality band "${params.band}"`);

  const [conditions, lethalTriggers] = await Promise.all([getEnabledConditions(env), getLethalTriggers(env)]);

  const statements = [];
  for (let i = 0; i < params.count; i++) {
    const seed = randomSeed();
    const generated = generateCandidate({
      pool,
      polygenicOneChance,
      robustnessOneChance: params.config.values.robustness_one_chance,
      ageMinGameDays: params.config.values.founding_age_min_game_days,
      ageMaxGameDays: params.config.values.founding_age_max_game_days,
      seed,
      lethalTriggers,
    });
    const sex = makeRng(deriveSeed(seed, 'sex')).pick(['mare', 'stallion'] as const);
    const { registeredName, originPrefix } = await resolveUniqueBarnName(env, seed);

    statements.push(
      ...buildFoundingHorseInsertStatements(env, {
        stableId: params.stable.id,
        sex,
        breedId: params.breed.id,
        breedCode: params.breed.code,
        registeredName,
        breederPrefix: originPrefix,
        bornGameDay: params.gameDay - generated.ageGameDays,
        genotype: generated.genotype,
        rngSeed: seed,
        worldTickSeq: params.worldTickSeq,
        estrousCycleTicks: params.config.values.estrous_cycle_ticks,
        conformationNoiseSd: params.config.values.conformation_noise_sd,
        conditions,
        lethalFoalDeathGameDays: params.config.values.lethal_foal_death_game_days,
        // No NPC stable has an account (this file's header comment) - null here means
        // buildConditionSignsEventStatement's own guard writes nothing, which is correct: its
        // horses foal nothing a child reads.
        accountId: null,
        // Slice 0011 §2.3/§7.1: an NPC stable's horses age and die on the same code path as
        // everyone else's (CLAUDE.md §13) - a lifespan is rolled for them here exactly like anyone
        // else's founding stock.
        lifespanConfig: params.config.values,
        // Slice 0013 §2.6/§5.2: an NPC stable's horses are stamped current every tick regardless
        // (noticeCareDue), but starting them current here too means they never read as overdue for
        // even the one tick between minting and the next tick running.
        careStartAgeGameDays: params.config.values.care_start_age_game_days,
        currentGameDay: params.gameDay,
      })
    );
  }

  await env.DB.batch(statements);
  return params.count;
}

/**
 * Tops the show barn up to targetSize Quarter Horses at the given quality band - idempotent in the
 * sense that pressing the button twice never over-fills it (slice 0008 §8.2), because it only ever
 * mints the shortfall.
 */
export async function stockShowBarn(
  env: Env,
  params: { config: Config; gameDay: number; worldTickSeq: number; targetSize: number; band: string }
): Promise<StockShowBarnResult> {
  const stable = await getShowBarnStable(env);
  if (!stable) {
    throw new Error('stockShowBarn: the NPC show barn stable is missing - has migrations/0040_npc_show_barn.sql been applied?');
  }
  // Breed-aware (docs/breed-ideal-vectors.md §6.2 step 1): createShowIfMissing already creates one
  // class per breed in play with an ideal vector, so a barn that only ever minted Quarter Horses
  // left every other breed's class with no NPC padding at all - a class with one player entry is a
  // class of one, and a player wins a national-sounding ribbon by being the only owner of a breed.
  // Tops each breed up to targetSize independently, same idempotent top-up-the-shortfall shape as
  // before, just once per breed instead of once overall.
  const breeds = (await getBreedsInPlay(env)).filter((b) => b.ideal_vector !== null);
  if (breeds.length === 0) throw new Error('stockShowBarn: no breed has an ideal_vector yet');

  const countsByBreed = await countAliveHorsesByBreedForStable(env, stable.id);

  let minted = 0;
  let alreadyHad = 0;
  for (const breed of breeds) {
    const breedAlreadyHad = countsByBreed.get(breed.id) ?? 0;
    alreadyHad += breedAlreadyHad;
    const shortfall = Math.max(0, params.targetSize - breedAlreadyHad);
    minted += await mintFoundingHorses(env, {
      stable,
      breed,
      config: params.config,
      gameDay: params.gameDay,
      worldTickSeq: params.worldTickSeq,
      count: shortfall,
      band: params.band,
    });
  }
  return { minted, alreadyHad };
}

/**
 * Slice 0015 §3.3/§7.3: "add an outcross batch" - the only way genetic material enters an NPC
 * stable's closed population (breeding stays same-stable-only, so left alone an NPC stable's own
 * COI only ever climbs). The generalised form of the mechanism underneath stockShowBarn: any NPC
 * stable, any breed with an ideal vector, picked from /admin/npc rather than hardcoded - and,
 * unlike stockShowBarn's top-up-to-a-target shape, mints exactly `count` new horses regardless of
 * how many the stable already has, since "add a batch" is not "top up to a total".
 */
export async function stockNpcStable(
  env: Env,
  params: { stableId: number; breedId: number; config: Config; gameDay: number; worldTickSeq: number; count: number; band: string }
): Promise<StockShowBarnResult> {
  const stable = await getStableById(env, params.stableId);
  if (!stable || stable.is_npc !== 1) throw new Error(`stockNpcStable: NPC stable ${String(params.stableId)} not found`);
  const breeds = await getBreeds(env);
  const breed = breeds.find((b) => b.id === params.breedId);
  if (!breed) throw new Error(`stockNpcStable: breed ${String(params.breedId)} not found`);

  const alreadyHad = await countAliveHorses(env, stable.id);
  const minted = await mintFoundingHorses(env, { stable, breed, config: params.config, gameDay: params.gameDay, worldTickSeq: params.worldTickSeq, count: params.count, band: params.band });
  return { minted, alreadyHad };
}

/** Slice 0015 §7.1: every is_npc stable's alive horses, for judgeOneClass's show-field top-up -
 * generalised from getShowBarnStable's single hardcoded stable to "every NPC stable's stock". */
export async function listNpcStableHorses(env: Env): Promise<HorseRow[]> {
  const result = await env.DB.prepare(
    `SELECT h.* FROM horses h JOIN stables s ON s.id = h.owner_stable_id WHERE s.is_npc = 1 AND h.status = 'alive'`
  ).all<HorseRow>();
  return result.results ?? [];
}
